test5

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,7 +41,7 @@ jobs:
 
       - name: Run Ansible Playbook
         run: |
-         ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini ansible/playbook.yml
+          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini ansible/playbook.yml
 
       - name: SSH and Deploy Docker Stack
         uses: appleboy/ssh-action@v1.0.0
@@ -50,7 +50,18 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            cd ~/yii-app
-            docker pull amanagraw35/yii-frontend:latest
-            docker pull amanagraw35/yii-backend:latest
-            docker stack deploy -c docker-stack.yml yii-app
+            if [ -d ~/yii-app ]; then
+              cd ~/yii-app
+            else
+              echo "Directory ~/yii-app does not exist"
+              exit 1
+            fi
+
+            if [ -f docker-stack.yml ]; then
+              sudo docker pull amanagraw35/yii-frontend:latest
+              sudo docker pull amanagraw35/yii-backend:latest
+              sudo docker stack deploy -c docker-stack.yml yii-app
+            else
+              echo "docker-stack.yml file not found"
+              exit 1
+            fi
